[project]
name = "10-langsmith-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.8",
    "langsmith>=0.4.28",
    "openevals>=0.1.0",
    "python-dotenv>=1.1.1",
]
